services:
  selenium:
    # https://github.com/seleniumhq-community/docker-seleniarm
    image: seleniarm/standalone-chromium:121.0
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"
    shm_size: "2gb"
